version: '3.7'
services:
  catgpt:
    container_name: catgpt
    image: "cr.yandex/crpdljjmir11npprksgk/catgpt:latest"
    restart: always
    network_mode: "host"
  unifiedagent:
    container_name: unifiedagent
    image: "cr.yandex/yc/unified-agent:latest"
    environment:
      FOLDER_ID: "b1g665agp5589ntuqkr1"
    restart: always
    network_mode: "host"
    volumes:
      - /ua:/etc/yandex/unified_agent/conf.d
